name: "Windows Installer"

on: workflow_dispatch

jobs:
  build-windows-installer:
    permissions:
      contents: write
    uses: ./.github/workflows/build.yml
    with:
      platform: "windows-latest"
      target: "x86_64-pc-windows-msvc"
      build-args: "--config src-tauri/tauri.unsigned.conf.json"
      sign-binaries: false
      asset-prefix: "handy-rtx"
      upload-artifacts: true
    secrets: inherit
